CREATE TABLE ADDRESS(ID INT PRIMARY KEY, HOUSE_NUMBER  INT,
    STREET_NAME VARCHAR(255),  CITY_NAME VARCHAR(255),
     ZIP_CODE VARCHAR(255), ADDRESS_TYPE INT );

INSERT  INTO  ADDRESS (:id, :house_number,:streetName, :city, :zip, : type)